Repository DesertRose2/desertrose, pull requests merged in 2021-03, with the labels that each got.

#68 Movespeed tweaks
  code/modules/mob/living/carbon/carbon_sprint.dm
  config/config.txt
  config/game_options.txt
Labels: Balance, Bugfix

#69 Even more rebase fixes
  BSQL.dll
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
  _maps/map_files/Pahrump/Pahrump_wip.dmm
  _maps/map_files/Pahrump/old/Pahrump.dmm
  _maps/map_files/Sunnyvale/Sunnyvale.dmm
  code/__DEFINES/sound.dm
  code/_globalvars/lists/maintenance_loot.dm
  code/controllers/subsystem/blackbox.dm
  code/datums/components/crafting/recipes/recipes_forge.dm
  code/datums/datacore.dm
  code/game/objects/effects/decals/remains.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/modules/admin/sql_message_system.dm
  code/modules/admin/topic.dm
  code/modules/client/client_procs.dm
  code/modules/client/verbs/aooc.dm
  code/modules/client/verbs/looc.dm
  code/modules/clothing/head/f13head.dm
  code/modules/fallout/obj/trash_stack.dm
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/job_types/ncr.dm
  code/modules/mining/machine_redemption.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_animal/corpse.dm
  code/modules/modular_computers/file_system/programs/crewmanifest.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  modular_citadel/code/modules/client/preferences_toggles.dm
  tgstation.dme
Labels: Bugfix

#75 Fixes worn items being consumed in crafting
  code/__HELPERS/_lists.dm
  code/datums/components/crafting/crafting.dm
Labels: Bugfix

#77 Fixes literally every reported, fixable rebase test bug.
  _maps/map_files/Pahrump/Dungeons.dmm
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/Pahrump_wip.dmm
  _maps/map_files/Pahrump/old/Pahrump.dmm
  _maps/map_files/StJeromes/StJeromesValley.dmm
  _maps/map_files/Sunnyvale/Sunnyvale.dmm
  _maps/map_files/generic/CentCom.dmm
  code/__DEFINES/inventory.dm
  code/__DEFINES/role_preferences.dm
  code/datums/explosion.dm
  code/game/gamemodes/gangs/dominator.dm
  code/game/gamemodes/gangs/dominator_countdown.dm
  code/game/gamemodes/gangs/gang.dm
  code/game/gamemodes/gangs/gang_datums.dm
  code/game/gamemodes/gangs/gang_decals.dm
  code/game/gamemodes/gangs/gang_hud.dm
  code/game/gamemodes/gangs/gang_items.dm
  code/game/gamemodes/gangs/gang_pen.dm
  code/game/gamemodes/gangs/gangs.dm
  code/game/gamemodes/gangs/gangtool.dm
  code/game/gamemodes/gangs/implant_gang.dm
  code/game/machinery/cryopod.dm
  code/game/objects/items/crayons.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/implants/implant_mindshield.dm
  code/game/objects/items/miscellaneous.dm
  code/modules/admin/topic.dm
  code/modules/clothing/suits/f13armor.dm
  code/modules/clothing/suits/f13factionarmor.dm
  code/modules/clothing/suits/f13suits.dm
  code/modules/fallout/misc/gang_items.dm
  code/modules/jobs/job_types/den.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/job_types/ncr.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/silicon/login.dm
  code/modules/projectiles/ammunition/ballistic/pistol.dm
  code/modules/projectiles/boxes_magazines/external/pistol.dm
  code/modules/projectiles/boxes_magazines/external/smg.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/surgery/organs/lungs.dm
  code/modules/vending/autodrobe.dm
  icons/obj/food/food.dmi
  modular_citadel/code/modules/client/loadout/hands.dm
  tgstation.dme
Labels: Bugfix, High Priority, High Risk

#79 Ports role whitelist from legacy
  code/__DEFINES/jobs.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/job.dm
  code/modules/client/preferences.dm
  code/modules/mob/dead/new_player/login.dm
  code/modules/mob/dead/new_player/new_player.dm
  config/config.txt
  tgstation.dme
Labels: Feature, High Priority

#80 Fixes loadout icon preview
  code/modules/asset_cache/asset_list_items.dm
Labels: Bugfix, High Priority

#81 Legion map fixes, torch/remains hotfixes
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  code/game/objects/effects/decals/remains.dm
  code/game/objects/items/candle.dm
Labels: Bugfix, High Priority

#74 Smelling Salts Port
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  code/modules/fallout/obj/smelling_salts.dm
  code/modules/mob/living/carbon/carbon.dm
  config/policy.txt
  icons/obj/fallout/smelling_salts.dmi
  tgstation.dme
Labels: Feature, High Priority

#83 Fixes NCR patrol ranger hat sprite, + blank sprite placeholder
  code/modules/clothing/head/f13factionhead.dm
  icons/obj/clothing/hats.dmi
Labels: Bugfix, High Priority

#84 Disables legacy ban/admin/mentor systems
  config/config.txt
Labels: Bugfix, High Priority

#85 fixes outdated motd, hub entry, and map name
  _maps/pahrump.json
  code/controllers/configuration/entries/general.dm
  code/game/world.dm
  code/modules/mapping/map_config.dm
  config/motd.txt
Labels: Bugfix, High Priority

#86 Emergency rebase test fixes
  code/datums/components/crafting/craft.dm
  code/datums/components/crafting/crafting.dm
  code/modules/fallout/turf/floor.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
Labels: Bugfix, High Priority, High Risk

#102 R&D Fixes
  _maps/map_files/Pahrump/Dungeons.dmm
  code/datums/materials/basemats.dm
  code/game/objects/items/stacks/bscrystal.dm
  code/modules/research/designs/bluespace_designs.dm
  code/modules/research/designs/weapon_designs.dm
  code/modules/research/stock_parts.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/research/techweb/nodes/bepis_nodes.dm
  code/modules/research/techweb/nodes/biotech_nodes.dm
  code/modules/research/techweb/nodes/bluespace_nodes.dm
  code/modules/research/techweb/nodes/computer_hud_nodes.dm
  code/modules/research/techweb/nodes/engineering_nodes.dm
  code/modules/research/techweb/nodes/mecha_nodes.dm
  code/modules/research/techweb/nodes/medical_nodes.dm
  code/modules/research/techweb/nodes/nanites_nodes.dm
  code/modules/research/techweb/nodes/robotics_nodes.dm
  code/modules/research/techweb/nodes/tools_nodes.dm
  code/modules/research/techweb/nodes/weaponry_nodes.dm
Labels: Balance, Bugfix, High Priority, Removal

#103 New Followers Map Changes
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
Labels: Feature

#112 Fixes #110
  code/modules/jobs/access.dm
Labels: Bugfix

#113 Fixes issue #97
  code/controllers/subsystem/overlays.dm
Labels: Bugfix

#116 Fixes carbon chunks appearing as plasma ore.
  code/game/turfs/simulated/minerals.dm
  code/modules/mining/ores_coins.dm
Labels: Bugfix

#114 Fixes gun melee attack cooldown.
  code/modules/projectiles/gun.dm
Labels: Bugfix

#117 Removes monkey cube biogenerator design.
  code/modules/research/designs/biogenerator_designs.dm
Labels: Feature, Removal

#104 Custom Ranger Outfit
  code/modules/clothing/head/f13head.dm
  code/modules/clothing/suits/f13armor.dm
  code/modules/clothing/under/accessories.dm
  code/modules/clothing/under/f13.dm
  icons/mob/clothing/accessories.dmi
  icons/mob/clothing/head.dmi
  icons/mob/clothing/suit.dmi
  icons/mob/clothing/uniform.dmi
  icons/obj/clothing/accessories.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/suits.dmi
Labels: Feature

#88 NCR Ranger Rework
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
  code/__DEFINES/jobs.dm
  code/__DEFINES/loadout.dm
  code/__DEFINES/melee.dm
  code/__DEFINES/radio.dm
  code/controllers/subsystem/blackbox.dm
  code/datums/martial/rangertakedown.dm
  code/game/communications.dm
  code/game/machinery/telecomms/machines/bus.dm
  code/game/machinery/telecomms/machines/hub.dm
  code/game/machinery/telecomms/machines/receiver.dm
  code/game/machinery/telecomms/machines/server.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/storage/belt.dm
  code/game/say.dm
  code/modules/client/preferences.dm
  code/modules/clothing/head/f13factionhead.dm
  code/modules/clothing/head/f13head.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/suits/f13armor.dm
  code/modules/clothing/under/accessories.dm
  code/modules/clothing/under/f13.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/jobs/job_types/ncr.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/living/say.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  icons/mob/clothing/hands.dmi
  icons/mob/clothing/head.dmi
  icons/mob/clothing/mask.dmi
  icons/mob/clothing/suit.dmi
  icons/mob/clothing/uniform.dmi
  icons/obj/card.dmi
  icons/obj/clothing/accessories.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/guns/projectile.dmi
  interface/stylesheet.dm
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/client/loadout/head.dm
  modular_citadel/code/modules/client/loadout/uniform.dm
  tgstation.dme
  tgui/packages/tgui-panel/chat/constants.js
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
  tgui/public/tgui-panel.bundle.css
  tgui/public/tgui-panel.bundle.js
Labels: Feature, Sprites

#45 Nooses: Frontier Justice
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/execution.dm
  code/game/objects/structures/kitchen_spike.dm
  icons/obj/gallows.dmi
  tgstation.dme
Labels: Feature, Refactor

#143 Bug squashing
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
  code/_globalvars/lists/maintenance_loot.dm
  code/game/machinery/autolathe.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/modules/clothing/head/f13factionhead.dm
  code/modules/clothing/head/f13head.dm
  code/modules/clothing/under/f13.dm
  code/modules/fallout/obj/spawners/lootdrops.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/projectiles/boxes_magazines/external/pistol.dm
  code/modules/projectiles/boxes_magazines/external/smg.dm
  code/modules/projectiles/guns/ballistic.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/research/designs/ammolathe_designs.dm
  code/modules/research/designs/biogenerator_designs.dm
  icons/mob/clothing/head.dmi
  icons/mob/clothing/uniform.dmi
  icons/obj/clothing/uniforms.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
Labels: Balance, Bugfix, Feature

#149 BoS Senior Knight Armor Re-Add, Head Scribe Ammo Fix
  code/modules/clothing/head/f13factionhead.dm
  code/modules/clothing/suits/f13factionarmor.dm
  code/modules/jobs/job_types/bos.dm
Labels: Bugfix

#190 Big fat faction reworks
  code/__DEFINES/jobs.dm
  code/_globalvars/lists/maintenance_loot.dm
  code/_onclick/drag_drop.dm
  code/datums/components/crafting/recipes/recipes_misc.dm
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/game/objects/items/granters.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/belt.dm
  code/modules/clothing/under/accessories.dm
  code/modules/crafting/items.dm
  code/modules/jobs/job_types/den.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/job_types/ncr.dm
  code/modules/jobs/job_types/wasteland.dm
  code/modules/jobs/job_whitelist.dm
  code/modules/jobs/jobs.dm
  code/modules/language/wayfarer.dm
  code/modules/projectiles/boxes_magazines/external/lmg.dm
  code/modules/projectiles/boxes_magazines/external/pistol.dm
  code/modules/projectiles/boxes_magazines/external/smg.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/laser_gatling.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/research/designs/ammolathe_designs.dm
  icons/fallout/objects/crafting.dmi
  icons/obj/ammo.dmi
  icons/obj/clothing/accessories.dmi
  icons/obj/guns/projectile.dmi
  icons/obj/guns/scopes.dmi
  icons/obj/items_and_weapons.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/client/loadout/head.dm
  tgstation.dme
Labels: Bugfix, Feature

#232 Suppressor changes.
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  icons/obj/guns/projectile.dmi
  icons/obj/guns/suppressors.dmi
Labels: Bugfix, Feature

#280 Legion Loadout Changes
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  code/__DEFINES/jobs.dm
  code/datums/martial/rangertakedown.dm
  code/game/objects/items/melee/misc.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/jobs.dm
Labels: Balance, Bugfix, Feature
