Repository DesertRose2/desertrose, pull requests merged in 2021-02, with the labels that each got.

#8 Fixes reagent ID typos, updates unit test
  code/modules/fallout/obj/trash/electronics.dm
  code/modules/reagents/chemistry/recipes/special.dm
  code/modules/rigsuits/modules/utility.dm
  code/modules/unit_tests/reagent_id_typos.dm
Labels: Bugfix, Feature

#9 Refactors the loadout icon system... again...
  code/modules/asset_cache/asset_list_items.dm
Labels: Bugfix, High Priority, Refactor

#10 Adds more unit tests and fixes some older ones, +readme
  code/modules/fallout/obj/food_and_drinks/food.dm
  code/modules/food_and_drinks/food/snacks_soup.dm
  code/modules/unit_tests/README.md
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/binary_insert.dm
  code/modules/unit_tests/combat.dm
  code/modules/unit_tests/component_tests.dm
  code/modules/unit_tests/confusion.dm
  code/modules/unit_tests/designs.dm
  code/modules/unit_tests/emoting.dm
  code/modules/unit_tests/initialize_sanity.dm
  code/modules/unit_tests/keybinding_init.dm
  code/modules/unit_tests/medical_wounds.dm
  code/modules/unit_tests/merge_type.dm
  code/modules/unit_tests/metabolizing.dm
  code/modules/unit_tests/outfit_sanity.dm
  code/modules/unit_tests/pills.dm
  code/modules/unit_tests/plantgrowth_tests.dm
  code/modules/unit_tests/projectiles.dm
  code/modules/unit_tests/reagent_mod_expose.dm
  code/modules/unit_tests/reagent_mod_procs.dm
  code/modules/unit_tests/resist.dm
  code/modules/unit_tests/say.dm
  code/modules/unit_tests/siunit.dm
  code/modules/unit_tests/spawn_mobs.dm
  code/modules/unit_tests/stomach.dm
  code/modules/unit_tests/surgeries.dm
Labels: High Priority, Refactor

#3 Mirrors PR #11110 from Aurorastation/Aurora.3
  code/modules/goonchat/browserOutput.dm
Labels: Bugfix, Performance

#7 wall icon fix
  code/modules/fallout/turf/walls.dm
Labels: Bugfix

#11 Replaced lockboxes with loot spawners
  _maps/map_files/Pahrump/Dungeons.dmm
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
  code/modules/clothing/under/miscellaneous.dm
Labels: Balance

#23 Even more CI fixes
  _maps/map_files/Sunnyvale/Sunnyvale.dmm
  _maps/map_files/VaultValley/vaultvalley-surface-1.dmm
  code/__HELPERS/unsorted.dm
  code/game/objects/effects/decals/cleanable/robots.dm
  code/game/objects/effects/spawners/bundle.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/modules/cargo/packs/armory.dm
  code/modules/cargo/packs/security.dm
  code/modules/library/random_books.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/combat.dm
  code/modules/unit_tests/outfit_sanity.dm
Labels: High Priority

#24 Linearmor tier bug fix
  code/modules/clothing/suits/f13factionarmor.dm
Labels: Bugfix, Runtime

#32 Init sanity + runtime fix
  code/__HELPERS/mobs.dm
  code/datums/brain_damage/imaginary_friend.dm
  code/datums/diseases/advance/symptoms/heal.dm
  code/datums/holocall.dm
  code/datums/mind.dm
  code/datums/wires/airlock.dm
  code/game/atoms.dm
  code/game/machinery/doors/alarmlock.dm
  code/game/machinery/slotmachine.dm
  code/game/objects/effects/anomalies.dm
  code/game/objects/effects/spawners/gibspawner.dm
  code/game/objects/items/stacks/stack.dm
  code/modules/antagonists/devil/devil.dm
  code/modules/awaymissions/corpse.dm
  code/modules/fields/fields.dm
  code/modules/fields/timestop.dm
  code/modules/mob/living/carbon/death.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/death.dm
  code/modules/mob/living/silicon/death.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_animal/bot/SuperBeepsky.dm
  code/modules/mob/living/simple_animal/friendly/dog.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/goliath_broodmother.dm
  code/modules/mob/living/simple_animal/hostile/regalrat.dm
  code/modules/mob/living/simple_animal/hostile/zombie.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/living/status_procs.dm
  code/modules/mob/mob.dm
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
  code/modules/reagents/chemistry/recipes/slime_extracts.dm
  code/modules/recycling/disposal/construction.dm
  code/modules/research/machinery/_production.dm
  code/modules/ruins/spaceruin_code/hilbertshotel.dm
Labels: Bugfix, High Priority, Runtime

#33 PR27 hotfix
  code/controllers/subsystem/mob_spawners.dm
  code/controllers/subsystem/monster_wave.dm
  code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm
Labels: Bugfix

#34 Fixes CI map choice and also fixes a long-standing runtime
  code/datums/shuttles.dm
  code/game/turfs/space/transit.dm
  code/modules/mapping/map_config.dm
Labels: Bugfix, Runtime

#47 Fixes bone looting and examining
  code/game/objects/effects/decals/remains.dm
Labels: Bugfix

#49 Fixes literally every typo with "it's" I could find
  code/__DEFINES/atmospherics.dm
  code/datums/martial/mushpunch.dm
  code/game/mecha/medical/medigax.dm
  code/game/objects/effects/decals/cleanable/humans.dm
  code/modules/antagonists/eldritch_cult/eldritch_magic.dm
  code/modules/awaymissions/away_props.dm
  code/modules/clothing/head/f13head.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/spacesuits/plasmamen.dm
  code/modules/clothing/suits/f13armor.dm
  code/modules/clothing/under/jobs/Plasmaman/civilian_service.dm
  code/modules/fallout/obj/crafting.dm
  code/modules/fallout/obj/structures/wasteplants.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/goliath_broodmother.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/polarbear.dm
  code/modules/mob/living/simple_animal/hostile/netherworld.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/clown.dm
  code/modules/mob/living/simple_animal/hostile/synth.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/research/designs/medical_designs.dm
  modular_citadel/code/modules/custom_loadout/custom_items.dm
  modular_citadel/code/modules/projectiles/guns/ballistic/rifles.dm
Labels: Spelling & Grammar

#51 Replaces BSQL with rust-g.
  .github/workflows/ci_suite.yml
  code/__DEFINES/bsql.config.dm
  code/__DEFINES/bsql.dm
  code/__DEFINES/rust_g.config.dm
  code/__HELPERS/roundend.dm
  code/__HELPERS/text.dm
  code/controllers/subsystem/blackbox.dm
  code/controllers/subsystem/dbcore.dm
  code/controllers/subsystem/mapping.dm
  code/modules/admin/DB_ban/functions.dm
  code/modules/admin/IsBanned.dm
  code/modules/admin/admin_ranks.dm
  code/modules/admin/banjob.dm
  code/modules/admin/create_poll.dm
  code/modules/admin/permissionedit.dm
  code/modules/admin/sql_message_system.dm
  code/modules/admin/topic.dm
  code/modules/bsql/LICENSE
  code/modules/bsql/core/connection.dm
  code/modules/bsql/core/library.dm
  code/modules/bsql/core/operation.dm
  code/modules/bsql/core/query.dm
  code/modules/bsql/includes.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/custom_loadout/read_from_db.dm
  code/modules/jobs/job_exp.dm
  code/modules/jobs/job_whitelist.dm
  code/modules/library/lib_machines.dm
  code/modules/library/random_books.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/dead/new_player/poll.dm
  code/modules/shuttle/emergency.dm
  dependencies.sh
  modular_citadel/code/modules/mentor/mentor_memo.dm
  tgstation.dme
  tools/ci/build_bsql.sh
  tools/ci/ci_config.txt
  tools/deploy.sh
Labels: High Priority, High Risk, Refactor

#58 More SQL hotfixes.
  SQL/populate_key_2018-07-09.py
  code/controllers/subsystem/blackbox.dm
  code/modules/admin/DB_ban/functions.dm
  code/modules/admin/permissionedit.dm
  code/modules/mob/dead/new_player/new_player.dm
Labels: Bugfix, High Priority

#60 Yet Another SQL Fix
  code/modules/admin/DB_ban/functions.dm
  code/modules/admin/permissionedit.dm
  code/modules/admin/sql_message_system.dm
Labels: Bugfix, High Priority

#61 Fixes randomly blank splashscreen, ports old ones
  config/title_screens/images/blank.dmi
  config/title_screens/images/title1.dmi
  config/title_screens/images/title1.png
  config/title_screens/images/title10.png
  config/title_screens/images/title11.png
  config/title_screens/images/title12.png
  config/title_screens/images/title13.dmi
  config/title_screens/images/title2.png
  config/title_screens/images/title3.png
  config/title_screens/images/title4.png
  config/title_screens/images/title5.png
  config/title_screens/images/title6.png
  config/title_screens/images/title7.png
  config/title_screens/images/title8.png
  config/title_screens/images/title9.png
Labels: Bugfix, High Priority

#64 Removes (Many) Unwanted Citadel Features
  code/__DEFINES/citadel_defines.dm
  code/__HELPERS/mobs.dm
  code/_globalvars/bitfields.dm
  code/datums/beepsky_fashion.dm
  code/game/objects/structures/bedsheet_bin.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/arousal/arousal.dm
  code/modules/arousal/genitals.dm
  code/modules/arousal/organs/breasts.dm
  code/modules/arousal/organs/penis.dm
  code/modules/arousal/organs/testicles.dm
  code/modules/arousal/organs/vagina.dm
  code/modules/arousal/organs/womb.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/holiday/halloween/bartholomew.dm
  code/modules/holiday/halloween/jacqueen.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/surgery/organs/vocal_cords.dm
  modular_citadel/code/modules/client/preferences_savefile.dm
  modular_citadel/code/modules/mob/cit_emotes.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/MKUltra.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/enlargement.dm
  modular_citadel/code/modules/reagents/chemistry/reagents/fermi_reagents.dm
  modular_citadel/code/modules/reagents/chemistry/recipes/fermi.dm
  tgstation.dme
Labels: Bugfix, High Priority, Removal

#65 Various rebase fixes.
  code/__DEFINES/construction.dm
  code/_onclick/hud/screen_objects.dm
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/modules/jobs/loadout_ingame.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
Labels: Bugfix, High Priority

#66 Re-fixes loadout.
  code/modules/jobs/loadout_ingame.dm
Labels: Bugfix, High Priority

#67 Fixes /structure bullets CanPass() to retain itself on its own scope
  code/game/objects/structures.dm
Labels: Bugfix

#54 Wall torches, Legion map tweaks, flickering lights
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  code/__HELPERS/unsorted.dm
  code/game/objects/items/candle.dm
  code/game/objects/structures/tribal_torch.dm
  code/game/turfs/simulated/walls.dm
  code/modules/power/lighting.dm
  icons/obj/candle.dmi
Labels: Balance, Bugfix, Feature
