Repository DesertRose2/desertrose, pull requests merged in 2021-05, with the labels that each got.

#497 Multilas Carbine
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/projectile/beams.dm
Labels: Stale

#521 Ammo Tweaks + Other Fixes
  _maps/map_files/Pahrump/Dungeons.dmm
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  code/_onclick/item_attack.dm
  code/game/machinery/doors/shutters.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/modules/mob/living/simple_animal/hostile/f13/deathclaw.dm
  code/modules/mob/living/simple_animal/hostile/f13/wastebots.dm
  code/modules/projectiles/projectile/bullets/revolver.dm
  code/modules/projectiles/projectile/bullets/rifle.dm
  code/modules/projectiles/projectile/special/ion.dm
Labels: Balance, Feature

#549 Projectile speed changes.
  code/_globalvars/lists/maintenance_loot.dm
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/game/objects/items/granters.dm
  code/modules/WVM/wvm.dm
  code/modules/crafting/items.dm
  code/modules/mob/living/simple_animal/hostile/f13/xray.dm
  code/modules/projectiles/ammunition/_firing.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/projectiles/projectile/bullets/sniper.dm
Labels: Balance, Feature

#550 Modkit tweak
  code/game/objects/items/modkit.dm
Labels: Feature

#551 Crusader pistol
  code/game/objects/items/modkit.dm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/ammunition/energy/plasma.dm
  code/modules/projectiles/boxes_magazines/external/rifle.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/research/designs/weapon_designs.dm
  code/modules/research/techweb/nodes/weaponry_nodes.dm
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/obj/guns/energy.dmi
  icons/obj/guns/projectile.dmi
Labels: Feature

#555 Luger
  code/game/objects/items/modkit.dm
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/client/loadout/kits.dm
Labels: Balance

#566 Veteran Ranger Loadout Fix
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  code/game/objects/items/storage/f13storage.dm
  code/modules/jobs/job_types/ncr.dm
Labels: Balance, Feature

#567 Update ncr.dm
  code/modules/jobs/job_types/ncr.dm
Labels: Balance, Feature
