Repository DesertRose2/desertrose, pull requests merged in 2021-04, with the labels that each got.

#322 R&D Fixes + Others
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
  code/datums/components/crafting/recipes/recipes_medicine.dm
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/game/machinery/autolathe.dm
  code/game/objects/items/stacks/medical.dm
  code/modules/jobs/job_types/den.dm
  code/modules/research/rdconsole.dm
Labels: Bugfix, Feature

#230 Power Armor Rework
  code/modules/clothing/head/f13head.dm
  code/modules/clothing/suits/f13armor.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/bullets/pistol.dm
Labels: Balance, Feature, Stale

#356 Custom Items
  code/game/objects/items/modkit.dm
  code/modules/clothing/suits/f13factionarmor.dm
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/client/loadout/kits.dm
Labels: Feature

#361 Minor road tweaks
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/VaultValley/vaultvalley-surface-1.dmm
Labels: Ready to Merge

#363 Update sql_message_system.dm
  code/modules/admin/sql_message_system.dm
Labels: Changes Required, Do Not Merge

#389 Fixes for my loadout
  icons/mob/clothing/eyes.dmi
  icons/mob/clothing/hands.dmi
  icons/mob/clothing/neck.dmi
  icons/obj/clothing/cloaks.dmi
Labels: conflict

#398 Crafting, Laser, Bunker and Other Tweaks
  _maps/map_files/templates/dungeons/north_sewer_1.dmm
  _maps/map_files/templates/dungeons/north_sewer_2.dmm
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/game/objects/structures/window.dm
  code/game/turfs/closed.dm
  code/modules/mining/machine_vending.dm
  code/modules/mob/living/simple_animal/hostile/f13/fallout_NPC.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/energy/laser.dm
Labels: Changes Required

#407 Nerfs tinkering armor speed, rebalances research
  code/controllers/subsystem/research.dm
  code/modules/crafting/items.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/research/techweb/nodes/biotech_nodes.dm
  code/modules/research/techweb/nodes/engineering_nodes.dm
  code/modules/research/techweb/nodes/misc_nodes.dm
  code/modules/research/techweb/nodes/tools_nodes.dm
  code/modules/research/techweb/nodes/weaponry_nodes.dm
  code/modules/vehicles/rubbish.dm
Labels: Changes Required, Merge Conflicts

#418 Small bugfixes, raider tweaks.
  code/datums/components/crafting/recipes/recipes_tailoring.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/modules/clothing/head/f13head.dm
  code/modules/clothing/suits/f13armor.dm
  code/modules/clothing/suits/f13factionarmor.dm
  code/modules/mob/living/simple_animal/corpse.dm
  code/modules/mob/living/simple_animal/hostile/f13/fallout_NPC.dm
  code/modules/mob/living/simple_animal/hostile/f13/raider.dm
  code/modules/projectiles/boxes_magazines/external/pistol.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  icons/mob/clothing/head.dmi
  icons/mob/clothing/suit.dmi
  icons/mob/wastemobs.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/guns/projectile.dmi
Labels: Balance, Bugfix, Feature

#390 Medical Changes
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/old/Pahrump.dmm
  code/game/objects/items/stacks/medical.dm
  code/modules/fallout/reagents/medicines.dm
  code/modules/jobs/job_types/followers.dm
  code/modules/reagents/chemistry/machinery/alchemy_table.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/reagent_containers/bottle.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagent_containers/patch.dm
  icons/obj/chemical.dmi
  icons/obj/reagentfillings.dmi
  icons/obj/stack_objects.dmi
  icons/obj/syringe.dmi
  tgstation.dme
  tgui/packages/tgui/interfaces/ChemMaster.js
  tgui/public/tgui.bundle.js
Labels: Balance, Do Not Merge, Feature, Refactor

#473 Bug fix crusaders
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/storage/belt.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
Labels: Bugfix

#472 Tweaks and Fluff.
  _maps/map_files/Pahrump/Dungeons.dmm
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
  _maps/map_files/Pahrump/old/Dungeons.dmm
  _maps/map_files/Pahrump/old/Pahrump.dmm
  code/_globalvars/lists/maintenance_loot.dm
  code/datums/components/crafting/recipes/recipes_forge.dm
  code/datums/components/crafting/recipes/recipes_misc.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/game/objects/items/cigs_lighters.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/f13storage.dm
  code/game/objects/items/storage/fancy.dm
  code/modules/fallout/obj/food_and_drinks/food.dm
  code/modules/fallout/obj/manual/ncr/ncr_job_guide.dm
  code/modules/fallout/obj/trash.dm
  code/modules/food_and_drinks/food/condiment.dm
  code/modules/food_and_drinks/food/snacks_pastry.dm
  code/modules/food_and_drinks/food/snacks_vend.dm
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_wastefood.dm
  code/modules/jobs/job_types/ncr.dm
  code/modules/mining/equipment/mining_tools.dm
  code/modules/mining/ores_coins.dm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/vending/cigarette.dm
  icons/fallout/trash.dmi
  icons/mob/clothing/mask.dmi
  icons/mob/inhands/weapons/melee_lefthand.dmi
  icons/mob/inhands/weapons/melee_righthand.dmi
  icons/obj/cigarettes.dmi
  icons/obj/cigarettes_pack.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/food/containers.dmi
  icons/obj/food/food.dmi
  icons/obj/items_and_weapons.dmi
  icons/obj/library.dmi
  icons/obj/ration_cig.dmi
  icons/obj/storage.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/client/loadout/head.dm
  tgstation.dme
Labels: Balance, Feature
